### ISSUE TITLE
Samples : Android manifest

### ISSUE THREAD

**Issue by Maxima078** [bitstadium/HockeySDK-Xamarin#115]
Hi,

I'm confused about Android manifest, reading your documentation it seems that when I want "android.permission.WRITE_EXTERNAL_STORAGE" I need to add "tools:node="replace"" right?
But from your sample project you do not use it: https://github.com/bitstadium/HockeySDK-Xamarin/blob/master/samples/HockeyAppSampleAndroid/Properties/AndroidManifest.xml

Maybe I missed something and there is some use cases where it could work without the replace?

**Comment by MatkovIvan** [comment]
Hi,

Thanks for getting in touch!
Since `5.0.0` we added [android:maxSdkVersion="18"](https://github.com/bitstadium/HockeySDK-Android/blob/5.0.0/hockeysdk/src/main/AndroidManifest.xml#L8) to manifest in our side, because (quote [ from android docs](https://developer.android.com/guide/topics/manifest/uses-permission-element.html))
> Beginning with Android 4.4 (API level 19), it's no longer necessary for your app to request the `WRITE_EXTERNAL_STORAGE` permission when your app wants to write to its own application-specific directories on external storage

So, if you didn't add `tools:node="replace"` into your manifest, this attribute will apply. Declaring the `tools:node="replace"` manifest merging strategy later in the dependency tree solves this problem and allows use `WRITE_EXTERNAL_STORAGE` permission in all android versions.

Probably this example a bit outdated, we'll check it.

Best,
Ivan
