### ISSUE TITLE
Apple Rejected our App because it's using a non-public API called setUserDescription

### ISSUE THREAD

**Issue by markmadlangbayan** [bitstadium/HockeySDK-Xamarin#57]
Hello, 

Have you run into this where Apple rejected the app because of non-public API usage?  In our case the setUserDescription.

-Mark

**Comment by TroubleMakerBen** [comment]
Hey Mark,

I'm sorry to hear that. The HockeySDK-iOS, which is wrapped by the HockeySDK-Xamarin, does not use any private API. This is unfortunately a widespread issue with Apple's Private API detection. We currently recommend appealing the rejection or simply resubmitting the same code with a new build number. We've heard of cases where this already fixes the problem. We've filed a Radar with Apple and we're hoping they are fixing this.

Best,
Benny

**Comment by SharpMobileCode** [comment]
Hi @TroubleMakerBen 

I see in the change log that this was fixed in v4.1.1

https://www.hockeyapp.net/help/sdk/ios/4.1.1/docs/docs/Changelog.html

However, the latest in Nuget is v4.1.0

https://www.nuget.org/packages/HockeySDK.Xamarin/

When can we see the update on Nuget?  We've got a deadline to get our app in the store, and we were reject because of this same issue.

**Comment by TroubleMakerBen** [comment]
Hey SharpMobileCode,

Actually, HockeySDK-Xamarin 4.1.0 wrapps the 4.1.1 version of our iOS SDK. I know, it's counter-intuitive. The reason for this is that HockeySDK-iOS 4.1.1 came in really hot and we chose not to change the Xamarin SDK's version. I will add a paragraph to our readme which underlying SDKs are used.

@markmadlangbayan 
From the issue that you are seeing, I'm assuming that you are using an older version of our SDK and not 4.1.0, updating the HockeySDK might be another "fix" for the issue.

PS:
I'm leaving this issue open in case others run into this. Please let us know if your app get's rejected because of this so we can add in that our collection of cases where Apple's detection caused a false-positive..

**Comment by SharpMobileCode** [comment]
@TroubleMakerBen 

Thanks for the response.  In that case, we are already using v4.1.0 from Nuget, but we still got reject due to:

"setUserDescription"

All of our searches on the strings and otool tools point to the HockeyAppSDK as the culprit.

**Comment by TroubleMakerBen** [comment]
@SharpMobileCode 
🤔 that's indeed very weird. We will definitely have a look into this. It might take a few days. There will be an update to our iOS SDK in a few days and we'll release an updated version of our Xamarin SDK, too, think 1-2 weeks.
But as I recommended above, appealing or resubmitting would be the way to go as we're definitely not using private API.

Thx in advance for your patience.

**Comment by TroubleMakerBen** [comment]
I just had a look. Looks like we didn't update the wrapper code, so it still uses the `setUserDescription`-wording.
We're working all hands on the iOS release and then let a Xamarin SDK update follow shortly after that.

Apologies for the inconvenience this causes you guys.

**Comment by SharpMobileCode** [comment]
Thanks for the feedback and appreciate you guys working on this!

**Comment by SharpMobileCode** [comment]
@TroubleMakerBen 

We're really in a bind right now and need a fix, so we're just fork and make the fix for ourselves so we can get this release.  So my question is this.  Is this the only place to make the update?

https://github.com/bitstadium/HockeySDK-Xamarin/blob/master/source/HockeySDK.iOSBindings/ApiDefinition.cs#L454

On this line, I assume we would change export statement from "userDescription" to "userProviderDescription"?  Would this get us going if we make this update, build and reference it ourselves?

Thanks!

**Comment by TroubleMakerBen** [comment]
If you provide a fix and submit a PR, I'll happily merge it.
Yes, the file you're referencing should be the one, the name of the property is `userProvidedDescription` and the code should look like this. I'd love to update the nuget real quick and all, but we're a little bit short in hands on deck this week.

```csharp
// @interface BITCrashMetaData : NSObject
    [BaseType (typeof (NSObject))]
    public partial interface BITCrashMetaData {

        // @property (copy, nonatomic) NSString * userDescription;
        [Export ("userProvidedDescription")]
        string UserProvidedDescription { get; set; }

        // @property (copy, nonatomic) NSString * userName;
        [Export ("userName")]
        string UserName { get; set; }

        // @property (copy, nonatomic) NSString * userEmail;
        [Export ("userEmail")]
        string UserEmail { get; set; }

        // @property (copy, nonatomic) NSString * userID;
        [Export ("userID")]
        string UserID { get; set; }
    }

```

**Comment by SharpMobileCode** [comment]
Will do!  Thanks!

**Comment by ranterle** [comment]
According to our sources Apple is aware of the issue and this should be fixed by now or very soon.
