### ISSUE TITLE
Migrating from Xamarin.Insights: Do not show "should I upload crashreport" messages

### ISSUE THREAD

**Issue by gentledepp** [bitstadium/HockeySDK-Xamarin#64]
Hi!

I just read in your docs, that whenever the app crashes and starts again, HockeyApp detects that there was a crash and in turn prompts the user a dialog, asking if it would be ok to send the crash reports to HockeyApps servers.

This dialog is currently not exisitng in Xamarin.Insights and we really cannot live with it.
That is because we are an ISV and in our business contract, there is a paragraph stating that in order to be able to for us comply with the support contract, they agree that all exceptions of their devices are being sent to our monitoring system - which is Xamarin.Insights until today.

Now if the end-users - which are not techies by the way - see this dialog, the propbility that thay do NOT accept it are quite high and we cannot see that something is going wrong.

So please can you make that dialog optional? That is be really really important to us.

**Comment by markmadlangbayan** [comment]
This is optional.  You can suppress the dialog.  We have it implemented on ios and android.  Unfortunately, i don't have access to our code right now.

-Mark




On Thu, Nov 17, 2016 at 4:23 AM -0600, "Alexander Marek" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

I just read in your docs, that whenever the app crashes and starts again, HockeyApp detects that there was a crash and in turn prompts the user a dialog, asking if it would be ok to send the crash reports to HockeyApps servers.

This dialog is currently not exisitng in Xamarin.Insights and we really cannot live with it.
That is because we are an ISV and in our business contract, there is a paragraph stating that in order to be able to for us comply with the support contract, they agree that all exceptions of their devices are being sent to our monitoring system - which is Xamarin.Insights until today.

Now if the end-users - which are not techies by the way - see this dialog, the propbility that thay do NOT accept it are quite high and we cannot see that something is going wrong.

So please can you make that dialog optional? That is be really really important to us.

-

**Comment by gentledepp** [comment]
Ok - that's awesome! Thanks! :)
