### ISSUE TITLE
SetCrashCallbacks - Why is it disabled?

### ISSUE THREAD

**Issue by hschmied** [bitstadium/HockeySDK-Xamarin#73]
May I ask why SetCrashCallbacks is disabled in the Xamarin-SDK?

I do have a workaround, where I set my own uncaught-exception handler, but I'd prefer to have hockey do the listening & checking, and just have it run some of my custom-code upon crash. Also, hockey notices that someone else is listening and puts out a warning message. So yeah, I'd like a nicer solution.

If setCrashCallbacks if off the table, any suggestions/best practice what to do instead?

Thanks!
-H

**Comment by TroubleMakerBen** [comment]
Hey Hannes,

That's a pretty good question and I needed to do some digging in our archives. ;)
We've deliberately not added the callbacks.
To begin with, having this callback was a pretty bad idea in hindsight and the new SDK we're building for [MobileCenter](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html) won't have this API. Post-crash-callbacks require a good understanding of what's possible and safe to do at crash time on iOS. A post crash callback would have the following constraints:
- no memory allocation
- no calls to any objective-c code but c/c++ code
- all c/c++ must be async-safe which limits the possibilities even further
We've encountered a lot of cases where people were doing very "interesting" things at crashtime and then got in touch with us because they assumed the HockeySDK was something wrong.

I guess that's probably not a very satisfying answer. That said, maybe [our API to attach data to a crash at the next launch](https://github.com/bitstadium/HockeySDK-Xamarin/blob/master/source/HockeySDK.iOSBindings/ApiDefinition.cs#L573) would be something that could solve the issue for you?

Let me know if you have more questions or feedback.

Benny
